# frozen_string_literal: true

BRINGIT_GIT_ROOT = File.expand_path('..', __dir__)
PERFORMANCE_TEST_REPO_SOURCE = 'https://gitlab.com/gitlab-org/git-memory-test.git'
PERFORMANCE_TEST_REPO_PATH = File.join(BRINGIT_GIT_ROOT, 'support/git-memory-test.git')

desc "Clone the test repo from #{PERFORMANCE_TEST_REPO_SOURCE}"
task :clone do
  unless File.exist?(PERFORMANCE_TEST_REPO_PATH)
    system('git', 'clone', '--bare', PERFORMANCE_TEST_REPO_SOURCE.to_s, '--', PERFORMANCE_TEST_REPO_PATH.to_s)
  end
end

desc "Remove the test repo in #{PERFORMANCE_TEST_REPO_PATH}"
task :clean do
  rm_rf PERFORMANCE_TEST_REPO_PATH
end

tests = []
Dir['test/*.rb'].each do |test_file|
  test_name = File.basename(test_file, '.rb')
  desc "Performance test: #{test_name}"
  task test_name => :clone do
    puts "Running performance test: #{test_name}"
    system('time', 'bundle', 'exec', 'ruby', '-Ilib', test_file.to_s, PERFORMANCE_TEST_REPO_PATH.to_s)
  end
  tests << test_name
end

desc 'Run all peformance tests'
task default: tests
